name: Gen keystore

on:
  workflow_dispatch:

jobs:
  gen:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 17

      - name: Generate persistent debug keystore
        run: |
          keytool -genkeypair -v -keystore debug.keystore -alias androiddebugkey -storepass android -keypass android -keyalg RSA -keysize 2048 -validity 10000 -dname "CN=Cvetochek, OU=Home, O=Home, C=RU"
          keytool -list -keystore debug.keystore -storepass android

      - name: Upload keystore
        uses: actions/upload-artifact@v4
        with:
          name: debug-keystore
          path: debug.keystore
